### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by javierdac** [Luehang/react-native-swipe-render#8]
**To Do First**
- [x ] Did you try latest release?
- [ ] Did you look for existing matching issues?

**Software Package Version:**

**Describe the bug**

Loop is not working property

**To Reproduce**
<SwipeRender
	data={[
		{ color: "blue" },
		{ color: "yellow" },
		{ color: "red" },
	]}
	renderItem={({ item, index }) => {
		return (
			<View key={"SwipeRender-slide#" + index} style={{flex: 1, backgroundColor: "#000"}}>
				<View
					style={{flex: 1, backgroundColor: item.color}}
				/>
			</View>
		);
	}}
	index={0} // default 0
	loop={false} // default false
	enableAndroidScrollView={false} // default false
	horizontal={true} // default true
	onIndexChanged={ (index) => { console.log(index)}}
/>

**Expected behavior**

if i change the loop to true, when i swipe will go to:
1.- blue
2.- yellow
3.- red 
4.- blue (but after 1 sec change again to red) **

**Version (please complete the following information):**
 - Device: [e.g. iPhone6]: Iphone 11 Simulator
 - Android:
 - iOS:
 - react-native: "0.61.2",
 - react: "16.9.0",

**Comment by Luehang** [comment]
Hi,

There has been a new update.  Please update package to latest.

## :gem: Update

```ssh
$ npm install --save react-native-swipe-render@latest
```

or

```ssh
$ yarn add react-native-swipe-render@latest
```
